name: Bug Report
description: Create a Bug Report to improve the product
title: "[BUG]: "
labels: ["type:suggestion", "scope:implementation"]
body:
    - type: textarea
      id: bug_description
      attributes:
        label: Bug Description
        description: Please describe how the bug manifests here.
      validations:
        required: true
    - type: textarea
      id: bug_expected_behavior
      attributes:
        label: Expected Behavior
        description: Please describe the beavior which is expected instead of the bug.
      validations:
        required: true
    - type: textarea
      id: bug_reproduction
      attributes:
        label: Steps to Reproduce
        description: Please describe how to reproduce the bug step by step.
      validations:
        required: true
    - type: textarea
      id: bug_solutions
      attributes:
        label: Possible Solutions
        description: If you are aware of a possible fix for the bug please describe it here.
      validations:
        required: false
    - type: textarea
      id: bug_further_info
      attributes:
        label: Further Information
        description: If you have further information such as system information or further source such as forum links, list it here. This section can also be used to add screenshots or other visual material to the report by attaching it to the text area.
      validations:
        required: false

